import type { PagedResult, PolizaDetail, PolizaListItem, PolizasCatalogs } from './polizasTypes'

export const polizasCatalogsFixture: PolizasCatalogs = {
  tipoPoliza: [
    { value: 'Vigor', label: 'En vigor' },
    { value: 'Pendiente', label: 'Pendiente' },
    { value: 'Anulada', label: 'Anulada' },
  ],
  compania: [{ value: 'Compania demo', label: 'Compania demo' }],
  ramo: [
    { value: 'Autos', label: 'Autos' },
    { value: 'Hogar', label: 'Hogar' },
  ],
  oficina: [
    { value: 'Las Palmas', label: 'Las Palmas' },
    { value: 'Tenerife', label: 'Tenerife' },
  ],
  division: [
    { value: 'Particulares', label: 'Particulares' },
    { value: 'Empresas', label: 'Empresas' },
  ],
  colaborador1: [
    { value: 'COL-01', label: 'Colaborador 1' },
    { value: 'COL-02', label: 'Colaborador 2' },
  ],
  administrativo: [
    { value: 'ADM-01', label: 'Administrativo 1' },
    { value: 'ADM-02', label: 'Administrativo 2' },
  ],
  comercial: [
    { value: 'COM-01', label: 'Comercial 1' },
    { value: 'COM-02', label: 'Comercial 2' },
  ],
  siniestros: [
    { value: 'SIN-01', label: 'Siniestros 1' },
    { value: 'SIN-02', label: 'Siniestros 2' },
  ],
  gestor: [
    { value: 'GES-01', label: 'Gestor 1' },
    { value: 'GES-02', label: 'Gestor 2' },
  ],
  canalCobro: [
    { value: 'Banco', label: 'Banco' },
    { value: 'Tarjeta', label: 'Tarjeta' },
  ],
  fraccionPago: [
    { value: 'Anual', label: 'Anual' },
    { value: 'Semestral', label: 'Semestral' },
    { value: 'Mensual', label: 'Mensual' },
  ],
  ccaa: [
    { value: 'Canarias', label: 'Canarias' },
    { value: 'Madrid', label: 'Madrid' },
  ],
  sexo: [
    { value: 'M', label: 'Mujer' },
    { value: 'H', label: 'Hombre' },
  ],
  estadoCivil: [
    { value: 'Soltero/a', label: 'Soltero/a' },
    { value: 'Casado/a', label: 'Casado/a' },
  ],
  regimenLaboral: [
    { value: 'Cuenta ajena', label: 'Cuenta ajena' },
    { value: 'Autonomo', label: 'Autonomo' },
  ],
  profesion: [
    { value: 'Administracion', label: 'Administracion' },
    { value: 'Ingenieria', label: 'Ingenieria' },
  ],
}

export const polizasDetailFixture: PolizaDetail[] = [
  {
    id: 'POL-1001',
    numero: 'POL-2026-0001',
    certificado: 'CERT-0001',
    tipoPoliza: 'Vigor',
    aplicacion: 'Auto',
    estado: 'Vigor',
    ramo: 'Autos',
    clienteId: 'CLI-001',
    clienteNombre: 'Cliente anonimo 1',
    compania: 'Compania demo',
    riesgo: '1234 ABC',
    fechaEfecto: '2026-01-01',
    fechaVencimiento: '2026-12-31',
    primaAnual: 420.5,
    moneda: 'EUR',
    oficina: 'Las Palmas',
    division: 'Particulares',
    colaborador1: 'COL-01',
    administrativo: 'ADM-01',
    comercial: 'COM-01',
    siniestros: 'SIN-01',
    gestor: 'GES-01',
    canalCobro: 'Banco',
    fraccionPago: 'Anual',
    ccaa: 'Canarias',
    documento: '00000001A',
    apellido1: 'Anonimo',
    apellido2: 'Uno',
    nombre: 'Cliente',
    sexo: 'M',
    fechaNacimiento: '1988-05-10',
    edad: 37,
    estadoCivil: 'Casado/a',
    hijos: 1,
    regimenLaboral: 'Cuenta ajena',
    profesion: 'Administracion',
    email: 'cliente1@example.test',
    telefono: '+34 600 000 001',
  },
  {
    id: 'POL-1002',
    numero: 'POL-2026-0002',
    certificado: 'CERT-0002',
    tipoPoliza: 'Pendiente',
    aplicacion: 'Hogar',
    estado: 'Pendiente',
    ramo: 'Hogar',
    clienteId: 'CLI-002',
    clienteNombre: 'Cliente anonimo 2',
    compania: 'Compania demo',
    riesgo: 'Vivienda demo',
    fechaEfecto: '2026-02-15',
    fechaVencimiento: '2027-02-14',
    primaAnual: 315.75,
    moneda: 'EUR',
    oficina: 'Tenerife',
    division: 'Particulares',
    colaborador1: 'COL-02',
    administrativo: 'ADM-02',
    comercial: 'COM-02',
    siniestros: 'SIN-02',
    gestor: 'GES-02',
    canalCobro: 'Tarjeta',
    fraccionPago: 'Semestral',
    ccaa: 'Canarias',
    documento: '00000002B',
    apellido1: 'Anonimo',
    apellido2: 'Dos',
    nombre: 'Cliente',
    sexo: 'H',
    fechaNacimiento: '1991-09-22',
    edad: 34,
    estadoCivil: 'Soltero/a',
    hijos: 0,
    regimenLaboral: 'Autonomo',
    profesion: 'Ingenieria',
    email: 'cliente2@example.test',
    telefono: '+34 600 000 002',
  },
]

function toListItem(detail: PolizaDetail): PolizaListItem {
  return {
    id: detail.id,
    numero: detail.numero,
    aplicacion: detail.aplicacion,
    estado: detail.estado,
    ramo: detail.ramo,
    clienteId: detail.clienteId,
    clienteNombre: detail.clienteNombre,
    documento: detail.documento,
    compania: detail.compania,
    riesgo: detail.riesgo,
    fechaEfecto: detail.fechaEfecto,
    fechaVencimiento: detail.fechaVencimiento,
    primaAnual: detail.primaAnual,
    moneda: detail.moneda,
  }
}

export const polizasFixture: PagedResult<PolizaListItem> = {
  page: 1,
  pageSize: 25,
  total: polizasDetailFixture.length,
  items: polizasDetailFixture.map(toListItem),
}
