import type { PagedResult, PolizaListItem, PolizasComponentMetadata } from './polizasTypes'

export const polizasMetadata: PolizasComponentMetadata = {
  resource: 'polizas',
  version: 1,
  appBuilder: {
    applicationId: 2,
    applicationVersion: 1,
    menuId: 10,
    rootComponentId: 2824,
    crudComponentId: 2825,
    componentDataSourceId: 354,
    dataSourceId: 146,
    dataSourceName: 'Pantalla_Polizas',
    modelObject: 'Pantalla_Polizas',
  },
  fields: [
    {
      name: 'numero',
      sourceField: 'Poliza',
      label: 'Poliza',
      type: 'string',
      filterable: true,
      sortable: true,
      visible: true,
      order: 3,
    },
    {
      name: 'aplicacion',
      sourceField: 'Aplicacion',
      label: 'Aplicacion',
      type: 'string',
      filterable: true,
      sortable: true,
      visible: true,
      order: 4,
    },
    {
      name: 'estado',
      sourceField: 'IdSituacion',
      label: 'Situacion',
      type: 'string',
      filterable: true,
      sortable: true,
      visible: true,
      order: 8,
    },
    {
      name: 'ramo',
      sourceField: 'IdRamo',
      label: 'Ramo',
      type: 'string',
      filterable: true,
      sortable: true,
      visible: true,
      order: 9,
    },
    {
      name: 'clienteNombre',
      sourceField: 'NombreCompleto',
      label: 'Cliente',
      type: 'string',
      filterable: true,
      sortable: true,
      visible: true,
      order: 40,
    },
    {
      name: 'compania',
      sourceField: 'Cia',
      label: 'Compania',
      type: 'string',
      filterable: true,
      sortable: true,
      visible: true,
      order: 1,
    },
    {
      name: 'fechaEfecto',
      sourceField: 'F_Efecto',
      label: 'Fecha efecto',
      type: 'date',
      filterable: false,
      sortable: true,
      visible: true,
      order: 20,
    },
    {
      name: 'fechaVencimiento',
      sourceField: 'F_Vencimiento',
      label: 'Fecha vencimiento',
      type: 'date',
      filterable: true,
      sortable: true,
      visible: true,
      order: 21,
    },
    {
      name: 'primaAnual',
      sourceField: 'PAnualCartera',
      label: 'Prima anual',
      type: 'money',
      filterable: true,
      sortable: true,
      visible: true,
      order: 39,
    },
  ],
}

export const polizasFixture: PagedResult<PolizaListItem> = {
  page: 1,
  pageSize: 25,
  total: 2,
  items: [
    {
      id: 'POL-1001',
      numero: 'POL-2026-0001',
      aplicacion: 'Auto',
      estado: 'Vigor',
      ramo: 'Autos',
      clienteId: 'CLI-001',
      clienteNombre: 'Cliente anonimo 1',
      compania: 'Compania demo',
      fechaEfecto: '2026-01-01',
      fechaVencimiento: '2026-12-31',
      primaAnual: 420.5,
      moneda: 'EUR',
    },
    {
      id: 'POL-1002',
      numero: 'POL-2026-0002',
      aplicacion: 'Hogar',
      estado: 'Pendiente',
      ramo: 'Hogar',
      clienteId: 'CLI-002',
      clienteNombre: 'Cliente anonimo 2',
      compania: 'Compania demo',
      fechaEfecto: '2026-02-15',
      fechaVencimiento: '2027-02-14',
      primaAnual: 315.75,
      moneda: 'EUR',
    },
  ],
}
